[SERVICE]
    flush           5
    log_level       error
    parsers_file    /fluent-bit/etc/parsers.conf

[INPUT]
    name            tail
    path            /var/lib/docker/containers/*/*-json.log
    parser          docker
    tag             app
    db              /var/log/flb/tail.db
    mem_buf_limit   5MB
    skip_long_lines on

[FILTER]
    name            parser
    match           app
    key_name        log
    parser          ecs
    reserve_data    on

[FILTER]
    name            nest
    match           app
    operation       lift
    nested_under    log
    add_prefix      log_

[OUTPUT]
    name            stackdriver
    match           app
    resource        gce_instance
    severity_key    log_level
