spring:
  application:
    name: highjoon-dev-backend
  config:
    import: optional:file:application-local.yml
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
