spring:
  application:
    name: highjoon-dev-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/highjoon_dev
    username: highjoon
    password: highjoon
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
