spring:
  application:
    name: highjoon-dev-backend
  config:
    import: optional:file:application-local.yml
  jpa:
    hibernate:
      ddl-auto: validate

app:
  cors:
    allowed-origins: http://localhost:3000

management:
  endpoints:
    web:
      exposure:
        include: health
